version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: postgres
    volumes:
      - /home/projects/pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindcare
    environment:
      - PORT=${PORT}
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
    volumes:
      - /home/projects/mindcare-backend:/app
